#==============================================================================
#	THE PLACE OF THE LOCAL GROUP IN THE COSMIC WEB
#==============================================================================
# Sebastian Bustamante (Universidad de Antioquia), macsebas33@gmail.com
# Jaime Forero-Romero (Universidad de los Andes)

#C Compiler
COMPILER = gcc

compile:
		$(COMPILER) Field_Cut16.c -o Field_Cut16.out
		@echo -e
		$(COMPILER) Field_Cut32.c -o Field_Cut32.out
		@echo -e
		$(COMPILER) Field_Cut_Plain.c -o Field_Cut_Plain.out
		@echo -e
		$(COMPILER) Density_Regions.c -o Density_Regions.out
		@echo -e
clean:
		rm -f *.out
		